name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SECRET_HOST }}
          username: ${{ secrets.SECRET_USER }}
          key: ${{ secrets.SECRET_SSH_KEY }}
          script: |
            cd /home/${{ secrets.SECRET_USER }}/${{ github.repository.name }}
            git pull origin main
