name: Deploy (Password SSH)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: SSH and Deploy using password
        env:
          HOST: ${{ secrets.SECRET_HOST }}
          USER: ${{ secrets.SECRET_USER }}
          PASS: ${{ secrets.SECRET_PASS }}
        run: |
          sshpass -p "$PASS" ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            cd /home/alwayson/file_upload
            git pull origin main
          EOF
